# Rebuild flakes for all available versions
name: Recreate R flakes

on:
  # Run every day at 1:30pm UTC
  schedule:
    - cron: "30 13 * * *"

    # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: nix build
        run: nix run .
      - uses: EndBug/add-and-commit@v9
