# Simple workflow for deploying static content to GitHub Pages
name: Recreate R flakes

on:

  schedule:
    - cron: "30 13 * * *"

    # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: nix build
        run: nix run .
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
